# Generated by Django 4.1.7 on 2023-03-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('about_title', models.CharField(max_length=50, verbose_name='About Title')),
                ('about', models.TextField(verbose_name='About')),
                ('button_text', models.CharField(max_length=57, verbose_name='Button Text')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('subimge', models.ImageField(upload_to='', verbose_name='Sub Image')),
            ],
        ),
    ]
