# Generated by Django 4.1.7 on 2023-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Activ Title')),
                ('about_title', models.CharField(max_length=50, verbose_name='Activ About Title')),
                ('about', models.TextField(verbose_name='Activ About')),
                ('button_text', models.CharField(max_length=57, verbose_name='Activ Button Text')),
                ('img', models.ImageField(upload_to='', verbose_name='Activ Image')),
                ('subimge', models.ImageField(upload_to='', verbose_name='Activ Sub Image')),
            ],
        ),
    ]
