# Generated by Django 4.1.6 on 2023-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activcarusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('div1_price', models.CharField(max_length=50, verbose_name='div-1 Title')),
                ('div1_about', models.TextField(verbose_name='div-1 About')),
                ('div1_img', models.ImageField(upload_to='', verbose_name='div-1 Img')),
                ('div2_price', models.CharField(max_length=50, verbose_name='div-2 Title')),
                ('div2_about', models.TextField(verbose_name='div-2 About')),
                ('div2_img', models.ImageField(upload_to='', verbose_name='div-2 Img')),
                ('div3_price', models.CharField(max_length=50, verbose_name='div-3 Title')),
                ('div3_about', models.TextField(verbose_name='div-3 About')),
                ('div3_img', models.ImageField(upload_to='', verbose_name='div-3 Img')),
                ('div4_price', models.CharField(max_length=50, verbose_name='div-4 Title')),
                ('div4_about', models.TextField(verbose_name='div-4 About')),
                ('div4_img', models.ImageField(upload_to='', verbose_name='div-4 Img')),
            ],
        ),
    ]
