# Generated by Django 4.1.6 on 2023-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='about_en_ca',
            field=models.TextField(null=True, verbose_name='Activ About'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='about_en_gb',
            field=models.TextField(null=True, verbose_name='Activ About'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='about_en_us',
            field=models.TextField(null=True, verbose_name='Activ About'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='about_title_en_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Activ About Title'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='about_title_en_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='Activ About Title'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='about_title_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Activ About Title'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='title_en_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Activ Title'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='title_en_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='Activ Title'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Activ Title'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='about_en_ca',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='about_en_gb',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='about_en_us',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='about_title_en_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='about_title_en_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='about_title_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='title_en_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='title_en_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
