# Generated by Django 4.1.6 on 2023-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_a_activcarusel_about_en_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activcarusel',
            name='button_text_en_ca',
            field=models.CharField(max_length=57, null=True, verbose_name='Activ Button Text'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='button_text_en_gb',
            field=models.CharField(max_length=57, null=True, verbose_name='Activ Button Text'),
        ),
        migrations.AddField(
            model_name='activcarusel',
            name='button_text_en_us',
            field=models.CharField(max_length=57, null=True, verbose_name='Activ Button Text'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='button_text_en_ca',
            field=models.CharField(max_length=57, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='button_text_en_gb',
            field=models.CharField(max_length=57, null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='carusel',
            name='button_text_en_us',
            field=models.CharField(max_length=57, null=True, verbose_name='Button Text'),
        ),
    ]
