# Generated by Django 4.1.6 on 2023-04-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_name_en_ca_category_name_en_gb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en_ca',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en_gb',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en_us',
        ),
    ]
