# Generated by Django 4.1.6 on 2023-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_category_name_en_ca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCategoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='Item Price')),
                ('img', models.ImageField(upload_to='', verbose_name='Item Image')),
                ('description', models.CharField(max_length=100, verbose_name='Item Description')),
                ('button_text', models.CharField(max_length=50, verbose_name='Item Button Text')),
            ],
        ),
    ]
