# Generated by Django 4.1.6 on 2023-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_activecategoryitems_button_text_en_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresitems',
            name='sub_ing',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Sub image'),
        ),
    ]
