# Generated by Django 4.1.6 on 2023-04-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_featuresitems_sub_ing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuresitems',
            old_name='sub_ing',
            new_name='sub_img',
        ),
    ]
