# Generated by Django 4.1.6 on 2023-04-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_featuresitems_sub_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresitems',
            name='sub_img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Sub image'),
        ),
    ]
