# Generated by Django 4.1.6 on 2023-04-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivCarusel',
        ),
    ]
