# Generated by Django 4.1.6 on 2023-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_productcategory_productsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_en_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_en_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_en_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='name_en_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Name'),
        ),
    ]
