# Generated by Django 4.1.6 on 2023-04-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_shopprod_button_text_en_ca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprod',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.productsubcategory'),
        ),
    ]
