# Generated by Django 4.1.6 on 2023-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_adminposts_alter_categoryitems_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminposts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
