# Generated by Django 4.1.6 on 2023-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_adminposts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminposts',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
