# Generated by Django 4.1.6 on 2023-04-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_adminposts_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminposts',
            name='time',
        ),
    ]
