# Generated by Django 4.1.6 on 2023-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_adminposts_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminposts',
            name='admin_name',
            field=models.CharField(default='None', max_length=255, verbose_name='Admin Name'),
        ),
    ]
