# Generated by Django 4.1.6 on 2023-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_adminposts_admin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=255, verbose_name='User Name')),
                ('message', models.TextField(verbose_name='Item Message')),
                ('img', models.ImageField(upload_to='', verbose_name='Post Image')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
