# Generated by Django 4.1.6 on 2023-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_usercomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminposts',
            name='description',
            field=models.TextField(verbose_name='Post Description'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='message',
            field=models.TextField(verbose_name='User Message'),
        ),
    ]
