# Generated by Django 4.1.6 on 2023-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_adminposts_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='username',
            field=models.CharField(max_length=255, verbose_name='User Name'),
        ),
    ]
